services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 5000:80
    volumes:
      - ./Frontend/dist/:/usr/share/nginx/html
  frontend:
    container_name: frontend
    build: ./Frontend/
    ports:
      - 5000:80